name: Deploy Angular App

on:
  push:
    branches:
      - main # Adjust the branch name as needed
  pull_request:
    branches:
     - main # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.10.0' # Adjust Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod
        
  commit_message_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit messages
        id: commit_message_check
        run: |
          commit_messages=$(git log --pretty=%s ${{ github.event.before }}..${{ github.sha }})
          errors=0
          for message in $commit_messages; do
            if [[ ! $message =~ ^[A-Z] ]]; then
              echo "ERROR: Commit message does not start with a capital letter: $message"
              errors=$((errors + 1))
            fi
          done
          if [ $errors -gt 0 ]; then
            echo "Found $errors commit message errors."
            exit 1
          else
            echo "Commit message check passed."
          fi

      - name: Set commit message check status
        if: always()
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = {
              name: 'Commit Message Check',
              conclusion: '${{ job.status }}',
              output: {
                title: 'Commit Message Check',
                summary: 'Commit message validation completed.',
              },
            };
            github.checks.create(context.repo, status)
            
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          
          BRANCH: gh-pages # Change to your GitHub Pages branch if different
          FOLDER: dist/demo-angular # Adjust folder path based on your Angular project structure
