name: Deploy Angular App

on:
  push:
    branches:
      - main # Adjust the branch name as needed
  pull_request:
    branches:
     - main # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.10.0' # Adjust Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          
          BRANCH: gh-pages # Change to your GitHub Pages branch if different
          FOLDER: dist/demo-angular # Adjust folder path based on your Angular project structure
